#-------------overlays-----------------#

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 4m0s
  path: ../../apps/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system