#
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 4m0s
  path: ../../apps/stagging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system