# CICD using GitHub actions

name: CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...
  
  code-quality:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

  update-newtag-in-helm-chart-in-registery:
    runs-on: ubuntu-latest

    needs: [push,code-quality]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

  Flux-helm-chart-update:
    runs-on: ubuntu-latest
    needs: update-newtag-in-helm-chart-in-registery
    steps:
    - name: Clone Flux Repo
      run: |
          git clone https://github.com/ManojKumarN001/platform_flux.git
          git config --global user.email "manojkumarn631@gmail.com"
          git config --global user.name "ManojKumarN001"
    
    - name: Update Helm Chart in Flux Repo
      run: |
       sed -i 's/tag:.*/tag: '"${{ github.sha }}"'/' helm/go-web-app-chart/values.yaml
       git add helm/go-web-app-chart/values.yaml
       git commit -m "Update image tag in Helm chart to ${{ github.sha }}"

    - name: Push Updated Helm Chart to Flux Repo
      run: |
        git push https://ManojKumarN001:${{ secrets.FLUX_REPO_TOKEN }}@github.com/ManojKumarN001/platform_flux.git main